let POIS=[], ROUTES=[], PLACES=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let map=null;
try{
  if(!window.maplibregl) throw new Error('MapLibre no cargado');
  map=new maplibregl.Map({container:'map',style:'https://demotiles.maplibre.org/style.json',center:[-8.356,42.209],zoom:13});
  map.addControl(new maplibregl.NavigationControl(),'top-right');
  map.addControl(new maplibregl.GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:true,showAccuracyCircle:true}),'top-right');
}catch(e){
  console.warn('Mapa no disponible',e);
  const m=document.querySelector('#map');
  if(m)m.innerHTML='<div style="padding:24px;color:#526057">El mapa no ha podido cargarse. Las fichas, rutas y núcleos siguen disponibles.</div>';
}
function status(){document.querySelector('#offline').textContent=navigator.onLine?'● En línea':'● Sin conexión'} addEventListener('online',status);addEventListener('offline',status);status();
Promise.all([1,2,3,4].map(i=>fetch(`data/pois-${i}.json`).then(r=>r.json())).concat([fetch('data/routes.json').then(r=>r.json()),fetch('data/places.json').then(r=>r.json())])).then(([p1,p2,p3,p4,r,n])=>{POIS=[...p1,...p2,...p3,...p4];ROUTES=r;PLACES=n;setup();}).catch(e=>{
  console.error('Error cargando datos locales',e);
  const s=document.querySelector('#stats');
  if(s)s.textContent='No se pudieron cargar los datos locales. Recarga la aplicación.';
});
function setup(){if(map)map.once('load',loadOfficialLayers);const types=[...new Set(POIS.map(x=>x.type))].sort();document.querySelector('#filter').innerHTML+=[...types].map(x=>`<option>${esc(x)}</option>`).join('');render();renderRoutes();renderPlaces();document.querySelector('#search').oninput=render;document.querySelector('#filter').onchange=render;renderMapPoints();}
function render(){let q=document.querySelector('#search').value.toLowerCase(), f=document.querySelector('#filter').value;let rows=POIS.filter(x=>(!f||x.type===f)&&(!q||Object.values(x).join(' ').toLowerCase().includes(q)));document.querySelector('#stats').textContent=`${rows.length} elementos · ${rows.filter(x=>x.coordinates).length} geolocalizados · ${rows.filter(x=>!x.coordinates).length} pendientes de coordenadas`;document.querySelector('#cards').innerHTML=rows.map(card).join('');document.querySelectorAll('[data-poi]').forEach(e=>e.onclick=()=>openPOI(e.dataset.poi));}
function card(x){let pend=!x.coordinates?'<span class="chip pending">Pendiente de coordenada</span>':'<span class="chip">En el mapa</span>';let ev=x.web_evidence?'<span class="chip">Existencia contrastada</span>':'';let priv=/privad/i.test(x.access)?'<span class="chip private">Acceso sensible</span>':'';return `<article class="card" data-poi="${esc(x.id)}"><h3>${esc(x.name)}</h3><div class="muted">${esc(x.area)}</div><div class="chips"><span class="chip">${esc(x.subtype)}</span>${pend}${ev}${priv}</div><div>${esc(x.description)}</div></article>`}
function openPOI(id){let x=POIS.find(p=>p.id===id);let web=x.web_source?`<b>Fuente cartográfica</b><span><a href="${esc(x.web_source)}" target="_blank" rel="noopener">${esc(x.web_source_label||'Ver fuente')}</a></span>`:'';let evidence=x.web_evidence?`<b>Contraste web</b><span>${esc(x.web_evidence)}${x.web_evidence_url?` · <a href="${esc(x.web_evidence_url)}" target="_blank" rel="noopener">fuente</a>`:''}</span>`:'';let coords=x.coordinates?`<b>Coordenadas</b><span>${x.coordinates[1].toFixed(6)}, ${x.coordinates[0].toFixed(6)}</span>`:'';document.querySelector('#detailbody').innerHTML=`<h2>${esc(x.name)}</h2><p>${esc(x.description)}</p><div class="detailgrid"><b>Zona</b><span>${esc(x.area)}</span><b>Tipo</b><span>${esc(x.type)} · ${esc(x.subtype)}</span><b>Estado</b><span>${esc(x.status)}</span>${coords}<b>Acceso</b><span>${esc(x.access)}</span><b>Por comprobar</b><span>${esc(x.verify)}</span><b>Experiencia</b><span>${esc(x.experience)}</span><b>Fuente de trabajo</b><span>${esc(x.source)}</span>${evidence}${web}</div>`;document.querySelector('#detail').showModal();if(map&&x.coordinates)map.flyTo({center:x.coordinates,zoom:17});}
document.querySelector('#close').onclick=()=>document.querySelector('#detail').close();
function renderRoutes(){document.querySelector('#routecards').innerHTML=ROUTES.map(r=>`<article class="card"><h3>${esc(r['Nombre provisional'])}</h3><div class="chips"><span class="chip">${esc(r['Tipo'])}</span><span class="chip">Base ${esc(r['Base disponible'])}</span></div><p>${esc(r['Paradas candidatas'])}</p>${r['Longitud']?`<p><b>${esc(r['Longitud'])}</b> · ${esc(r['Duración'])} · ${esc(r['Dificultad'])}</p>`:''}<div class="muted"><b>Estado:</b> ${esc(r['Estado'])}<br><b>Siguiente:</b> ${esc(r['Trabajo siguiente'])}${r['Recorrido oficial']?`<br><b>Recorrido:</b> ${esc(r['Recorrido oficial'])}`:''}</div></article>`).join('')}
function renderPlaces(){document.querySelector('#placecards').innerHTML=PLACES.map(x=>`<article class="card place" data-place="${esc(x.id)}"><h3>${esc(x.name)}</h3><div class="chips"><span class="chip">Núcleo oficial</span><span class="chip">PBA</span></div><div class="muted">${x.coordinates[1].toFixed(6)}, ${x.coordinates[0].toFixed(6)}</div></article>`).join('');document.querySelectorAll('[data-place]').forEach(e=>e.onclick=()=>{let x=PLACES.find(p=>p.id===e.dataset.place);if(map)map.flyTo({center:x.coordinates,zoom:16});});}
function renderMapPoints(){if(!map)return;let located=POIS.filter(x=>x.coordinates);located.forEach(x=>new maplibregl.Marker().setLngLat(x.coordinates).setPopup(new maplibregl.Popup().setHTML(`<b>${esc(x.name)}</b><br>${esc(x.area)}<br><small>Patrimonio geolocalizado</small>`)).addTo(map));PLACES.forEach(x=>{let el=document.createElement('div');el.className='place-marker';el.title=x.name;new maplibregl.Marker({element:el}).setLngLat(x.coordinates).setPopup(new maplibregl.Popup().setHTML(`<b>${esc(x.name)}</b><br><small>Núcleo oficial · PBA</small>`)).addTo(map)});let all=[...located.map(x=>x.coordinates),...PLACES.map(x=>x.coordinates)];if(all.length){let b=new maplibregl.LngLatBounds();all.forEach(x=>b.extend(x));map.fitBounds(b,{padding:70,maxZoom:14});}}

async function loadOfficialLayers(){if(!map)return;
  const layers=[
    {id:'parish',url:"https://ideg.xunta.gal/servizos/rest/services/LimitesAdministrativos/LimitesAdministrativos/MapServer/18/query?where="+encodeURIComponent("CONCELLO='Covelo' AND PARROQUIA LIKE '%Lamosa%'")+"&outFields=CONCELLO,PARROQUIA,CODIGOINE&returnGeometry=true&outSR=4326&f=geojson",add:(data)=>{map.addSource('parish-official',{type:'geojson',data});map.addLayer({id:'parish-fill',type:'fill',source:'parish-official',paint:{'fill-color':'#315c48','fill-opacity':0.08}});map.addLayer({id:'parish-line',type:'line',source:'parish-official',paint:{'line-color':'#244b3a','line-width':3,'line-dasharray':[2,2]}});}},
    {id:'prg119',url:"https://ideg.xunta.gal/servizos/rest/services/CatalogoPaisaxesGalicia/CPG_ValorPaisaxistico_Panoramicos_2/MapServer/6/query?where="+encodeURIComponent("DENOMINACI='PR-G 119 Ruta do Xabriña'")+"&outFields=CODIGO,DENOMINACI&returnGeometry=true&outSR=4326&f=geojson",add:(data)=>{map.addSource('prg119-official',{type:'geojson',data});map.addLayer({id:'prg119-line',type:'line',source:'prg119-official',paint:{'line-color':'#168a50','line-width':4,'line-opacity':0.9}});}},
    {id:'hydro',url:"https://ideg.xunta.gal/servizos/rest/services/Hidrografia/Hidrografia/MapServer/0/query?where=1%3D1&geometry=-8.40%2C42.18%2C-8.31%2C42.25&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&outFields=*&returnGeometry=true&outSR=4326&f=geojson",add:(data)=>{map.addSource('hydro-official',{type:'geojson',data});map.addLayer({id:'hydro-line',type:'line',source:'hydro-official',paint:{'line-color':'#3578a8','line-width':2,'line-opacity':0.8}});}}
  ];
  let ok=0;
  for(const l of layers){try{const r=await fetch(l.url);if(!r.ok)throw new Error(r.status);const data=await r.json();if(data.features?.length){l.add(data);ok++;}}catch(e){console.warn('Capa oficial no disponible:',l.id,e);}}
  const badge=document.querySelector('#officialLayers');if(badge) badge.textContent=`Capas Xunta: ${ok}/3 cargadas`;
}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')});
if('serviceWorker'in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
let installPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;const b=document.querySelector('#install');if(b)b.hidden=false;});
document.querySelector('#install')?.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;document.querySelector('#install').hidden=true;});
window.addEventListener('appinstalled',()=>{const b=document.querySelector('#install');if(b)b.hidden=true;});